### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by jcruz** [cs121-team-panda/coconut-interpreter-react#14]
Low priority tasks
- [x] Fix Output component tests
- [x] Write tests for PersistentDrawer component
  - [x] Fix Editor component tests
- [x] Fix `overflow: hidden` hack in PersistentDrawer (height problem)
- [x] Flow type PersistentDrawer component (instead of prop-types)
- [x] Fix grid layout on small screens
- [x] Figure out why `@babel/core` package is required
- [x] ~~Drawer subheader label (compilation parameters)~~ won't do
- [x] ~~Highlight gutter instead of line~~ won't do
- [x] ~~Disable foldable code in the gutter~~ won't do
- [x] ~~Option to change editor theme~~ won't do
- [x] Fix ace editor width when drawer is open
- [x] Create isError selector for OutputContainer to pass in as prop to Output
- [x] Remove `typeface-roboto` package
- [x] Remove css-modules linting
- [x] Button tooltips
- [x] Run button shortcut
- [x] Move compilation parameters settings to redux store

**Comment by mjenrungrot** [comment]
`react` uses `babel 6`. However, our libraries require `@babel/core 7.0.0-beta.38+`
Note: Dev team is waiting for the official release of babel 7
Ref: https://github.com/facebook/react/issues/12548

**Comment by jcruz** [comment]
@mjenrungrot 78f2ced1b8894b27ce0eef3683d845bb82c54401 Upgraded `react-scripts` package which includes the `@babel/core` version we require.
