### ISSUE TITLE
Loading dots after stderr are red

### ISSUE THREAD

**Issue by nkadonaga** [cs121-team-panda/coconut-interpreter-react#30]
steps to reproduce

1. run faulty code

![screen shot 2018-04-11 at 9 41 37 pm](https://user-images.githubusercontent.com/8051724/38656745-577bd2ac-3dd1-11e8-89d5-4ee36fde69ab.png)

2. run something else

![screen shot 2018-04-11 at 9 42 29 pm](https://user-images.githubusercontent.com/8051724/38656751-66ebcd96-3dd1-11e8-9016-8d40397ae29e.png)

**Comment by nkadonaga** [comment]
Aha! This also:

![screen shot 2018-04-11 at 10 32 52 pm](https://user-images.githubusercontent.com/8051724/38658070-673147e8-3dd8-11e8-80d0-827a7c97cb93.png)

**Comment by jcruz** [comment]
@nkadonaga Steps to reproduce the last one?

Edit: nevermind, happens on every running error. Fixed in #31.
