### ISSUE TITLE
[feature] Stop execution

### ISSUE THREAD

**Issue by jcruz** [cs121-team-panda/coconut-interpreter-react#38]
Be able to cancel a current request before the 30 second timeout.

https://redux-saga.js.org/docs/advanced/TaskCancellation.html
https://github.com/redux-saga/redux-saga/issues/651

**Comment by mjenrungrot** [comment]
How are we going to handle the backend? And, do we need specific error messages if we stop the execution early?

**Comment by jcruz** [comment]
It may be bad practice, but we'll just let the backend run into the timeout since I don't think it's possible to easily kill/timeout the exec command. I think there shouldn't be an error message since the user stopped it.

**Comment by mjenrungrot** [comment]
I think at the moment the backend does not have any timeout, right? It just has the timeout on AWS Lambda but not local server.

**Comment by jcruz** [comment]
Yup only thinking about production

**Comment by jcruz** [comment]
Moved to https://github.com/cs121-team-panda/coconut-interpreter/issues/87
